### ISSUE TITLE
Upgrade to 2009.22

### ISSUE THREAD

**Issue by rgl** [zunderscore/chocolatey-packages#10]
Can you please upgrade to https://github.com/microsoft/cascadia-code/releases/tag/v2009.22?

**Comment by zunderscore** [comment]
Yep, didn't realize they reissued 2009.21 with the new version number. Will get out as soon as I can.

**Comment by rgl** [comment]
I'm trying to upgrade it :-)

BTW, What do you think about moving from azure pipelines to github actions?

**Comment by zunderscore** [comment]
Not on my list of priorities at the moment but something I may consider in the future. Since PR #11 just got merged in, closing this issue. Thanks for the feedback!
